### ISSUE TITLE
invisible file inside the container

### ISSUE THREAD

**Issue by 3th3r** [linuxserver/docker-medusa#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS, centos 7

Dokcer Command line : 
docker create \

  --name=medusa \
-v /path/config:/config \
-v /path/dl/:/mnt/downloads \
-v /path/media:/mnt/video \
-e PGID=<GID>-e PUID=<UID>  \
-e TZ=<TZ> \
-p 8081:8081 \
  linuxserver/medusa:latest

No log for docker, (no visible error)
No symlink, <path> is mounted trough cifs-utils (to keep windows permission intact, on smb share, from freenas 11)

############
So, my problem,

Within the docker container, some files are invisible.
Some files and folder are not visible, but if I copy them (with windows, freenas, the host, or inside the container) they are visible. But if I rename them (to there initial name) they disaper .... 
Its happening only on this container. 

I use a bunch of your docker image (plex, sickrag, nginx etc ...) And this problem only appears in this container.

To be more specific, the incriminated files, are visible, through the windows share on windows. 
Visible on Freenas
Visible on the host machine
And visilble on an other docker container (PLEX) running on the same host

Good joob team linux:server, I used a lot of your image. And exept this little issue I never had a problem.
THX

**Comment by OmgImAlexis** [comment]
You may need to give more info, what do you mean by "Within the docker container, some files are invisible".

Are you setting the `UUID` and `GUID` correctly?
Can you see the files when you're logged into the `root` user?
Can you run `ls -lah` in the directory so we can see the file and directory permissions?

**Comment by 3th3r** [comment]
Hey, 
Yes uid adn gid are set correctly. I can read write on my mount volume.
Same issue logged as root. 

If I copy a "missing" file, the missing and copy will show in the container, but if I delete one of them, both disapear. 
And if I managed to "show" the file in the container, and rename it (to the name; who wasn't showing) it disapears. But only on the container. These files are still visible on Windows, on the host or in the Plex Container.

And the permission seems to be good, all file / folder set to good user. Same for mount drive.

**Comment by OmgImAlexis** [comment]
Sounds like it's not mounted with the correct permissions or it's not mounted in the right location.

PING @sparklyballs

**Comment by 3th3r** [comment]
But it is. I use the UID and GID as my mounted drive.
Mounted with the correct server credentials.
I use this same id's in other docker image, and it works perfectly.

And if it was a permission issue, all the content will be inaccessible, not only a few files.
I've test this docker image on other machine, and does the same.

I think it comes from the images itself, not a "permission problem".

**Comment by j0nnymoe** [comment]
Your mounts are different to what's listed in our readme, I suspect the application is moving stuff to the wrong location.

```
-v <path to downloads>:/downloads \ 
-v <path to tv-shows>:/tv \
```
Try with these mounts and see if you get the same issue.

**Comment by 3th3r** [comment]
I thought, my actual path waren't relevant to the problem.

But if you insist :

docker create \
  --name=medusa \
-v /home/pvr/medusa/config:/config \
-v /mnt/NAS/Downloads/torrent/Anime:/mnt/downloads/Anime \
-v /mnt/NAS/Downloads/torrent/TV_Show/:/mnt/downloads/TV_Show \
-v /mnt/NAS/Media/Video/TvShow:/mnt/video/TvShow \
-v /mnt/NAS/Media/Video/Anime:/mnt/video/Anime \
-e PGID=1001 -e PUID=1001  \
-e TZ=Europ/Paris \
-p 8081:8081 \
  linuxserver/medusa:latest

The actual docker run used for the image.
I've used similar one, with other of image, without any problem/

**Comment by OmgImAlexis** [comment]
What're you using in medusa while processing? Any chance you're using symlink or copy?

**Comment by OmgImAlexis** [comment]
If you are using symlinks try this instead. You'll need to change your settings in Medusa but this should fix it.

```shell
docker create 
--name=medusa 
-v /home/pvr/medusa/config:/config 
-v /mnt/NAS/Downloads/torrent/Anime:/mnt/NAS/Downloads/torrent/Anime
-v /mnt/NAS/Downloads/torrent/TV_Show:/mnt/NAS/Downloads/torrent/TV_Show
-v /mnt/NAS/Media/Video/TvShow:/mnt/NAS/Media/Video/TvShow
-v /mnt/NAS/Media/Video/Anime:/mnt/NAS/Media/Video/Anime
-e PGID=1001 -e PUID=1001 
-e TZ=Europ/Paris 
-p 8081:8081 
linuxserver/medusa:latest
```

**Comment by 3th3r** [comment]
Thank's I'll try.

**Comment by 3th3r** [comment]
I've try and didn't fix the issue.
I've test an other image of medusa, and it worked fine.
So i guess it comes from the image.

**Comment by OmgImAlexis** [comment]
You'll need to provide more details. I've used Docker for over 2 years now and the only time I've ever had this issue is when mounts weren't setup properly.

Can you show us `docker inspect medusa` and let us know what config settings you have for post-processing. You've likely got something incorrect somewhere and it's causing the medusa to move the file inside of the container instead of into your mounted filesystem.

**Comment by 3th3r** [comment]
I'm also using docker for several years.
And it's the first time I've seen this. 

This probleme apears with clean docker image, with all the file reseted. And some files are steal invisible.
I don't say, it comes from your image. But something incompatible with my host / NAS / windows File permission.

I can't give you a docker inspect. Your Medusa, encounter a serious bug. And though it was the time to redownload all my library. Crashing my dedicated server and messing with my backlog. So I've deleted it. 

For info, I've notice before reinstalling and installing an other version. But your image come with more 1000+ commit of, from the github.

Maybe a bad image pull.

**Comment by sparklyballs** [comment]
you haven't supplied the results of `ls -lah` on the affected folders nor have you given results of docker inspect

btw shouldn't it be  Europe/Paris

**Comment by sparklyballs** [comment]
user hasn't supplied the information asked for 

closing with advice to user to open another issue only if they're willing to provide the requested information
